services:
    static:
        build:
            dockerfile: .docker/test/Dockerfile
            context: .
        entrypoint: ["make", "static"]
        profiles: ["static-analyze"]
        environment:
            APP_ENV: "test_cached"
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
        volumes:
            - ./:/srv/sylius:delegated
            - .docker/test/php.ini:/etc/php/8.2/fpm/php.ini:delegated
            - .docker/test/php.ini:/usr/local/etc/php/php-cli.ini:delegated
        networks:
            - sylius
    
    behat:
        build:
            dockerfile: .docker/test/Dockerfile
            context: .
        entrypoint: ["make", "phpunit-integration"]
        profiles: ["integration"]
        environment:
            APP_ENV: "test_cached"
            APP_DEBUG: 0
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%"
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
            SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN: "sync://"
            SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN: "sync://"
            SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN: "sync://"
            SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN: "sync://"
        volumes:
            - ./:/srv/sylius:delegated
            - .docker/test/php.ini:/etc/php/8.2/fpm/php.ini:delegated
            - .docker/test/php.ini:/usr/local/etc/php/php-cli.ini:delegated
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:5.7
        profiles: ["integration"]
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        networks:
            - sylius

networks:
    sylius:
        driver: bridge
